version: '2.3'
services:
  redis:
    image: redislabs/redisgraph:2.2.5
    ports:
      - "6379:6379"

  service:
    image: registry.insight-centre.org/sit/mps/object-detection-service:master
    command: echo "ok"
    runtime: nvidia
    # volumes:
      # - "./:/service"
    build:
      context: '.'
      dockerfile: 'Dockerfile'